export { CategoryService, type Category } from './category-service.js';
export { ItemService, type Item } from './item-service.js';
export { ComparisonService, type Comparison } from './comparison-service.js';
export { TemplateService, type ComparisonTemplate, type ComparisonAttribute, type AttributeDataType } from './template-service-prisma.js';
export type { Result } from './category-service.js';
export { BrandService, MerchantService, type Brand, type Merchant, type MerchantVerification, type MerchantBranch } from './merchant-brand-prisma.js';
export { CatalogService, type CatalogItem, type ItemMedia, type ItemRelation } from './catalog-service-prisma.js';
export { PriceEngine, type PriceEntry, type Offer } from './price-engine-prisma.js';
export { InventoryService, PricingConsole, CampaignService, type InventoryEntry, type PriceRule, type Campaign } from './merchant-portal-service.js';
export { ReviewService, type Review, type ReviewStats } from './review-service-prisma.js';
