/**
 * Requirement Coverage Matrix, the real HTML/Markdown Test Report (PDF is
 * NOT built this pass — same honest, deliberate scope decision already
 * established by Document Generation Engine's own export function), and
 * Migration Validation — a real, working example of the "Universal
 * Validation Principle": this engine can validate the Universal
 * Comparison Engine's own real results, never a fabricated migration
 * sign-off.
 */
import { sharedPool } from './db-pool.js';
import { TestCaseService } from './testing-engine.js';
import { TestExecutionService } from './test-execution-service.js';
import { UniversalComparisonEngine } from './universal-comparison-engine.js';

export interface RequirementCoverageRow {
  requirementId: string; requirement: string; totalCases: number; executed: number;
  passed: number; failed: number; blocked: number; coveragePercent: number; defectIds: string[];
}

export interface TestReport {
  clientId: string; generatedAt: string;
  totals: { total: number; pass: number; fail: number; blocked: number; skipped: number; notExecuted: number; notApplicable: number };
  passPercent: number; coveragePercent: number;
  coverage: RequirementCoverageRow[];
  environmentMatrix: { environment: string; browser: string; device: string; count: number }[];
  defectsBySeverity: Record<'low' | 'medium' | 'high' | 'critical', number>;
  finalRecommendation: 'PASS' | 'PASS_WITH_RISKS' | 'FAIL' | 'BLOCKED';
  knownLimitations: string[];
}

const KNOWN_LIMITATIONS = [
  'Automated Playwright execution against arbitrary client environments is not wired into this engine — executions are recorded by a human tester or a future automation pass, never fabricated by this engine itself.',
  'Cross-browser/cross-device execution is recorded manually per the environment/browser/device fields on each execution — there is no automated matrix runner yet.',
  'PHYSICAL DEVICE TESTING NOT AVAILABLE — only Playwright-class emulation is modeled; no physical device farm is connected.',
  'PDF binary export is not built — HTML and Markdown exports are real and complete (same scope decision already made for Document Generation Engine).',
  'External test-management sync (TestRail/Jira/Azure DevOps) is architecture-only this pass — see test-management-adapter.ts — no live credentials are configured for any client yet.',
  'Video/trace evidence capture is not automated — the evidence model supports a reference to one if a human/tool supplies it.',
  'Performance and accessibility test cases generated by this engine are explicitly labeled CANDIDATES, not executed benchmarks — no load-testing or automated a11y tool is wired in yet.',
];

export class TestReportService {
  async getCoverageMatrix(clientId: string): Promise<RequirementCoverageRow[]> {
    const res = await sharedPool.query(
      `SELECT r.id AS requirement_id, r.title,
              COUNT(DISTINCT tc.id) AS total_cases,
              COUNT(DISTINCT CASE WHEN latest.status IS NOT NULL AND latest.status != 'not_executed' THEN tc.id END) AS executed,
              COUNT(DISTINCT CASE WHEN latest.status = 'pass' THEN tc.id END) AS passed,
              COUNT(DISTINCT CASE WHEN latest.status = 'fail' THEN tc.id END) AS failed,
              COUNT(DISTINCT CASE WHEN latest.status = 'blocked' THEN tc.id END) AS blocked
       FROM oc_business_requirements r
       LEFT JOIN traceability_links tl ON tl.target_type = 'business_requirement' AND tl.target_id = r.id AND tl.link_type = 'tests' AND tl.source_type = 'test_case'
       LEFT JOIN test_cases tc ON tc.id = tl.source_id
       LEFT JOIN LATERAL (SELECT status FROM test_executions WHERE test_case_id = tc.id ORDER BY executed_at DESC LIMIT 1) latest ON true
       WHERE r.client_id = $1
       GROUP BY r.id, r.title ORDER BY r.title`,
      [clientId]
    );
    const rows: RequirementCoverageRow[] = [];
    for (const r of res.rows) {
      const defectRes = await sharedPool.query(
        `SELECT id FROM test_defects WHERE client_id = $1 AND requirement_source_type = 'business_requirement' AND requirement_source_id = $2 AND status != 'closed'`,
        [clientId, r.requirement_id]
      );
      rows.push({
        requirementId: r.requirement_id, requirement: r.title, totalCases: Number(r.total_cases),
        executed: Number(r.executed), passed: Number(r.passed), failed: Number(r.failed), blocked: Number(r.blocked),
        coveragePercent: Number(r.total_cases) > 0 ? Math.round((Number(r.executed) / Number(r.total_cases)) * 1000) / 10 : 0,
        defectIds: defectRes.rows.map(d => d.id),
      });
    }
    return rows;
  }

  async generateReport(clientId: string): Promise<TestReport> {
    const [casesRes, coverage, defectsRes] = await Promise.all([
      sharedPool.query(
        `SELECT tc.id, latest.status FROM test_cases tc
         LEFT JOIN LATERAL (SELECT status FROM test_executions WHERE test_case_id = tc.id ORDER BY executed_at DESC LIMIT 1) latest ON true
         WHERE tc.client_id = $1 AND tc.status = 'active'`,
        [clientId]
      ),
      this.getCoverageMatrix(clientId),
      sharedPool.query(`SELECT severity, status FROM test_defects WHERE client_id = $1`, [clientId]),
    ]);

    const totals = { total: casesRes.rows.length, pass: 0, fail: 0, blocked: 0, skipped: 0, notExecuted: 0, notApplicable: 0 };
    for (const row of casesRes.rows) {
      const status = row.status || 'not_executed';
      if (status === 'pass') totals.pass++;
      else if (status === 'fail') totals.fail++;
      else if (status === 'blocked') totals.blocked++;
      else if (status === 'skipped') totals.skipped++;
      else if (status === 'not_applicable') totals.notApplicable++;
      else totals.notExecuted++;
    }
    const executed = totals.total - totals.notExecuted - totals.notApplicable;
    const passPercent = executed > 0 ? Math.round((totals.pass / executed) * 1000) / 10 : 0;
    const coveragePercent = totals.total > 0 ? Math.round(((totals.total - totals.notExecuted) / totals.total) * 1000) / 10 : 0;

    const envRes = await sharedPool.query(
      `SELECT environment, browser, device, COUNT(*) AS cnt FROM test_executions WHERE client_id = $1
       AND (environment != '' OR browser != '' OR device != '') GROUP BY environment, browser, device ORDER BY cnt DESC`,
      [clientId]
    );
    const environmentMatrix = envRes.rows.map(r => ({ environment: r.environment, browser: r.browser, device: r.device, count: Number(r.cnt) }));

    const defectsBySeverity: TestReport['defectsBySeverity'] = { low: 0, medium: 0, high: 0, critical: 0 };
    let openCriticalOrHigh = 0;
    for (const d of defectsRes.rows) {
      defectsBySeverity[d.severity as 'low' | 'medium' | 'high' | 'critical']++;
      if (['critical', 'high'].includes(d.severity) && !['closed', 'wont_fix', 'duplicate'].includes(d.status)) openCriticalOrHigh++;
    }

    // Real, documented (not fabricated-precision) recommendation rule:
    // FAIL only if a genuinely open critical/high defect exists; PASS_WITH_RISKS
    // if any lower-severity fail/blocked or coverage gaps remain; BLOCKED only if
    // nothing meaningful has been executed yet; PASS only when everything active
    // has been executed with zero fails/blocked.
    let finalRecommendation: TestReport['finalRecommendation'];
    if (openCriticalOrHigh > 0) finalRecommendation = 'FAIL';
    else if (totals.total > 0 && executed === 0) finalRecommendation = 'BLOCKED';
    else if (totals.fail > 0 || totals.blocked > 0 || totals.notExecuted > 0) finalRecommendation = 'PASS_WITH_RISKS';
    else finalRecommendation = 'PASS';

    return {
      clientId, generatedAt: new Date().toISOString(), totals, passPercent, coveragePercent, coverage,
      environmentMatrix, defectsBySeverity, finalRecommendation, knownLimitations: KNOWN_LIMITATIONS,
    };
  }

  exportHtml(report: TestReport, clientName: string): string {
    const recLabel: Record<TestReport['finalRecommendation'], string> = {
      PASS: 'PASS', PASS_WITH_RISKS: 'PASS WITH RISKS', FAIL: 'FAIL', BLOCKED: 'BLOCKED',
    };
    const rows = report.coverage.map(c => `<tr><td>${esc(c.requirementId)}</td><td>${esc(c.requirement)}</td><td>${c.totalCases}</td><td>${c.executed}</td><td>${c.passed}</td><td>${c.failed}</td><td>${c.coveragePercent}%</td><td>${c.defectIds.length}</td></tr>`).join('');
    const envRows = report.environmentMatrix.map(e => `<tr><td>${esc(e.environment || '—')}</td><td>${esc(e.browser || '—')}</td><td>${esc(e.device || '—')}</td><td>${e.count}</td></tr>`).join('');
    return `<h1>AskABD Test Execution Report</h1>
<p><strong>Client:</strong> ${esc(clientName)} &nbsp; <strong>Generated:</strong> ${esc(report.generatedAt)}</p>
<h2>Executive Summary</h2>
<ul>
<li>Total Tests: ${report.totals.total}</li>
<li>Passed: ${report.totals.pass}</li>
<li>Failed: ${report.totals.fail}</li>
<li>Blocked: ${report.totals.blocked}</li>
<li>Skipped: ${report.totals.skipped}</li>
<li>Not Executed: ${report.totals.notExecuted}</li>
<li>Pass %: ${report.passPercent}%</li>
<li>Coverage %: ${report.coveragePercent}%</li>
</ul>
<h2>Requirement Coverage</h2>
<table border="1" cellpadding="4"><thead><tr><th>Requirement ID</th><th>Requirement</th><th>Test Cases</th><th>Executed</th><th>Passed</th><th>Failed</th><th>Coverage</th><th>Open Defects</th></tr></thead><tbody>${rows || '<tr><td colspan="8">No requirements recorded yet.</td></tr>'}</tbody></table>
<h2>Environment / Browser / Device Matrix (real, recorded only)</h2>
<table border="1" cellpadding="4"><thead><tr><th>Environment</th><th>Browser</th><th>Device</th><th>Executions</th></tr></thead><tbody>${envRows || '<tr><td colspan="4">No executions recorded with environment/browser/device detail yet.</td></tr>'}</tbody></table>
<h2>Defect Summary</h2>
<ul><li>Critical: ${report.defectsBySeverity.critical}</li><li>High: ${report.defectsBySeverity.high}</li><li>Medium: ${report.defectsBySeverity.medium}</li><li>Low: ${report.defectsBySeverity.low}</li></ul>
<h2>Known Limitations</h2>
<ul>${report.knownLimitations.map(l => `<li>${esc(l)}</li>`).join('')}</ul>
<h2>Final Recommendation: ${recLabel[report.finalRecommendation]}</h2>`;
  }

  exportMarkdown(report: TestReport, clientName: string): string {
    const rows = report.coverage.map(c => `| ${c.requirementId} | ${c.requirement} | ${c.totalCases} | ${c.executed} | ${c.passed} | ${c.failed} | ${c.coveragePercent}% | ${c.defectIds.length} |`).join('\n');
    return `# AskABD Test Execution Report

**Client:** ${clientName} **Generated:** ${report.generatedAt}

## Executive Summary
- Total Tests: ${report.totals.total}
- Passed: ${report.totals.pass}
- Failed: ${report.totals.fail}
- Blocked: ${report.totals.blocked}
- Not Executed: ${report.totals.notExecuted}
- Pass %: ${report.passPercent}%
- Coverage %: ${report.coveragePercent}%

## Requirement Coverage
| Requirement ID | Requirement | Test Cases | Executed | Passed | Failed | Coverage | Open Defects |
|---|---|---|---|---|---|---|---|
${rows || '| — | No requirements recorded yet. | | | | | | |'}

## Known Limitations
${report.knownLimitations.map(l => `- ${l}`).join('\n')}

## Final Recommendation: ${report.finalRecommendation.replace('_', ' ')}
`;
  }

  /**
   * Real "Universal Validation Principle" example: validates a real
   * Universal Comparison Engine run rather than fabricating a migration
   * sign-off. Creates a real regression test case + a real execution
   * whose PASS/FAIL is driven directly by the comparison's own stored
   * summary — never re-guessed.
   */
  async runMigrationValidation(clientId: string, comparisonRunId: string, actor: string | null) {
    const comparisonEngine = new UniversalComparisonEngine();
    const run = await comparisonEngine.getRun(comparisonRunId);
    if (!run || run.clientId !== clientId) throw new Error('Comparison run not found for this client.');
    if (run.status !== 'completed') throw new Error(`Comparison run is "${run.status}", not "completed" — cannot validate an incomplete comparison.`);

    const title = `Migration schema parity: ${run.leftLabel} vs ${run.rightLabel}`;
    const caseService = new TestCaseService();
    const existing = await sharedPool.query(`SELECT id FROM test_cases WHERE client_id = $1 AND title = $2 AND category = 'regression'`, [clientId, title]);
    const testCase = existing.rows[0]
      ? await caseService.get(existing.rows[0].id)
      : await caseService.createManual(clientId, {
          title, description: `Real, automatically-tracked migration parity check between ${run.leftLabel} and ${run.rightLabel}.`,
          expectedResult: 'Zero schema differences (0 mismatch/missing/extra) between source and target.', category: 'regression', priority: 'high', severity: 'high',
        }, actor);
    if (!testCase) throw new Error('Could not create or find the migration validation test case.');

    const totalDiffs = run.summary.mismatch + run.summary.missing + run.summary.extra + run.summary.unknown;
    const actualResult = `${run.summary.match} matched, ${run.summary.missing} missing, ${run.summary.extra} extra, ${run.summary.mismatch} mismatched, ${run.summary.unknown} unknown (of ${run.summary.total} tables).`;
    const executionService = new TestExecutionService();
    const execution = await executionService.recordExecution(clientId, testCase.id, {
      status: totalDiffs === 0 ? 'pass' : 'fail', actualResult,
      evidence: [{ type: 'database_evidence', description: 'Universal Comparison Engine run', reference: run.id }],
    }, actor);
    return { testCase, execution };
  }
}

function esc(s: string): string {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
