export interface CatalogService {
  id: string;
  name: string;
  category: 'assessment' | 'operations' | 'transformation' | 'governance' | 'support' | 'financial' | 'platform' | 'intelligence';
  description: string;
  businessValue: string;
  deliverables: string[];
  prerequisites: string[];
  requiredInformation: string[];
  expectedTimeline: string;
  dependencies: string[];
  outputs: string[];
}

export const serviceCatalog: CatalogService[] = [
  // ─── Assessment ─────────────────────────────────────────────────────────────
  { id: 'architecture-review', name: 'Architecture Review', category: 'assessment', description: 'Comprehensive evaluation of system architecture, patterns, and technical decisions', businessValue: 'Identify architectural risks, technical debt, and improvement opportunities', deliverables: ['Architecture Assessment Report', 'Gap Analysis', 'Recommendations'], prerequisites: ['Architecture documentation'], requiredInformation: ['Architecture diagrams', 'Technology stack'], expectedTimeline: '2-4 weeks', dependencies: [], outputs: ['Assessment Report', 'Risk Register'] },
  { id: 'security-assessment', name: 'Security Assessment', category: 'assessment', description: 'Vulnerability assessment, security posture review, and compliance gap analysis', businessValue: 'Reduced security risk, compliance readiness', deliverables: ['Security Report', 'Vulnerability List', 'Remediation Plan'], prerequisites: ['Infrastructure access'], requiredInformation: ['Network diagrams', 'Security policies'], expectedTimeline: '2-3 weeks', dependencies: [], outputs: ['Security Assessment', 'Risk Register'] },
  { id: 'cloud-assessment', name: 'Cloud Assessment', category: 'assessment', description: 'Cloud readiness evaluation, migration planning, and cost optimization', businessValue: 'Cloud strategy clarity, cost optimization, migration confidence', deliverables: ['Cloud Assessment', 'Migration Plan', 'Cost Analysis'], prerequisites: ['Infrastructure documentation'], requiredInformation: ['Infrastructure inventory', 'Dependencies'], expectedTimeline: '2-4 weeks', dependencies: [], outputs: ['Cloud Strategy', 'Migration Roadmap'] },
  { id: 'performance-assessment', name: 'Performance Assessment', category: 'assessment', description: 'Load testing, capacity planning, and performance optimization', businessValue: 'Optimized performance, capacity confidence', deliverables: ['Performance Report', 'Capacity Plan'], prerequisites: ['Application access'], requiredInformation: ['Traffic patterns', 'SLA targets'], expectedTimeline: '1-3 weeks', dependencies: [], outputs: ['Performance Report', 'Optimization Actions'] },
  { id: 'devops-assessment', name: 'DevOps Assessment', category: 'assessment', description: 'Evaluate CI/CD maturity, deployment practices, and automation opportunities', businessValue: 'Faster delivery, fewer failures', deliverables: ['DevOps Maturity Report', 'Pipeline Design'], prerequisites: ['Repository access'], requiredInformation: ['CI/CD configuration', 'Deployment frequency'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Maturity Report', 'Improvement Roadmap'] },
  { id: 'business-analysis', name: 'Business Analysis', category: 'assessment', description: 'Requirements gathering, process mapping, and business capability assessment', businessValue: 'Clear requirements, optimized processes', deliverables: ['Business Requirements', 'Process Maps'], prerequisites: ['Stakeholder access'], requiredInformation: ['Business processes', 'KPIs'], expectedTimeline: '2-6 weeks', dependencies: [], outputs: ['Requirements Document', 'Capability Assessment'] },
  { id: 'root-cause-analysis', name: 'Root Cause Analysis', category: 'assessment', description: 'Deep investigation into system failures using evidence-based analysis', businessValue: 'Permanent resolution, reduced recurrence', deliverables: ['RCA Report', 'Corrective Actions'], prerequisites: ['Incident data'], requiredInformation: ['Logs', 'Deployment history'], expectedTimeline: '3-5 days', dependencies: [], outputs: ['RCA Report', 'Action Items'] },
  { id: 'database-assessment', name: 'Database Assessment', category: 'assessment', description: 'Database health, performance, schema analysis, and optimization', businessValue: 'Improved query performance, data integrity', deliverables: ['Database Health Report', 'Optimization Plan'], prerequisites: ['Database access'], requiredInformation: ['Schema', 'Query patterns', 'Growth projections'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Health Report', 'Index Recommendations'] },

  // ─── Operations ─────────────────────────────────────────────────────────────
  { id: 'monitoring-setup', name: 'Monitoring & Observability', category: 'operations', description: 'End-to-end monitoring for infrastructure, applications, and business metrics', businessValue: 'Proactive issue detection, reduced MTTR', deliverables: ['Monitoring Dashboard', 'Alert Configuration'], prerequisites: ['Infrastructure access'], requiredInformation: ['Server inventory', 'SLA targets'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Live Dashboards', 'Alert Rules'] },
  { id: 'incident-management', name: 'Incident Management', category: 'operations', description: 'Structured incident response, root cause analysis, and resolution tracking', businessValue: 'Faster resolution, reduced business impact', deliverables: ['Incident Process', 'RCA Templates'], prerequisites: ['Monitoring'], requiredInformation: ['System logs', 'Contact list'], expectedTimeline: 'Ongoing', dependencies: ['monitoring-setup'], outputs: ['Incident Reports', 'Preventive Actions'] },
  { id: 'managed-support', name: 'Managed Support', category: 'operations', description: '24/7 operational support, incident management, and proactive maintenance', businessValue: 'Reduced operational burden, faster resolution', deliverables: ['Support SLA', 'Incident Response'], prerequisites: ['Monitoring'], requiredInformation: ['Escalation matrix', 'SLA targets'], expectedTimeline: 'Ongoing', dependencies: ['monitoring-setup'], outputs: ['SLA Reports', 'Incident Resolutions'] },
  { id: 'backup-recovery', name: 'Backup & Disaster Recovery', category: 'operations', description: 'Automated backup strategy, disaster recovery planning and testing', businessValue: 'Data protection, business continuity', deliverables: ['Backup Strategy', 'DR Plan', 'Recovery Procedures'], prerequisites: ['Infrastructure access'], requiredInformation: ['RPO/RTO targets', 'Critical systems'], expectedTimeline: '2-3 weeks', dependencies: [], outputs: ['DR Plan', 'Recovery Runbooks'] },
  { id: 'scheduler-automation', name: 'Scheduler & Automation', category: 'operations', description: 'Automated task scheduling, job management, and workflow automation', businessValue: 'Reduced manual effort, consistent execution', deliverables: ['Scheduled Jobs', 'Automation Rules'], prerequisites: ['API access'], requiredInformation: ['Job definitions', 'Frequency'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Job Configuration', 'Execution Reports'] },

  // ─── Transformation ─────────────────────────────────────────────────────────
  { id: 'digital-transformation', name: 'Digital Transformation', category: 'transformation', description: 'End-to-end transformation planning from current state to target architecture', businessValue: 'Business modernization, competitive advantage', deliverables: ['Transformation Roadmap', 'Business Case'], prerequisites: ['Business analysis', 'Architecture review'], requiredInformation: ['Business strategy', 'Target state'], expectedTimeline: '4-12 weeks', dependencies: ['business-analysis'], outputs: ['Transformation Strategy', 'Phased Roadmap'] },
  { id: 'application-modernization', name: 'Application Modernization', category: 'transformation', description: 'Legacy application assessment and modernization planning', businessValue: 'Reduced technical debt, improved agility', deliverables: ['Modernization Assessment', 'Migration Strategy'], prerequisites: ['Application access'], requiredInformation: ['Application inventory', 'Dependencies'], expectedTimeline: '4-8 weeks', dependencies: ['architecture-review'], outputs: ['Modernization Strategy', 'Migration Plan'] },
  { id: 'cloud-migration', name: 'Cloud Migration', category: 'transformation', description: 'Structured cloud migration execution with validation and rollback', businessValue: 'Infrastructure modernization, cost optimization', deliverables: ['Migration Plan', 'Execution', 'Validation'], prerequisites: ['Cloud assessment'], requiredInformation: ['Migration targets', 'Dependencies'], expectedTimeline: '4-16 weeks', dependencies: ['cloud-assessment'], outputs: ['Migrated Infrastructure', 'Validation Report'] },
  { id: 'database-migration', name: 'Database Migration', category: 'transformation', description: 'Database migration planning, execution, validation, and rollback', businessValue: 'Data platform modernization with safety', deliverables: ['Migration Plan', 'Execution', 'Validation', 'Rollback'], prerequisites: ['Database assessment'], requiredInformation: ['Schema', 'Data volumes', 'Downtime window'], expectedTimeline: '2-8 weeks', dependencies: ['database-assessment'], outputs: ['Migrated Database', 'Validation Evidence'] },
  { id: 'optimization-service', name: 'Continuous Optimization', category: 'transformation', description: 'Ongoing performance, cost, and operational optimization', businessValue: 'Continuous improvement, cost reduction', deliverables: ['Optimization Findings', 'Improvement Actions'], prerequisites: ['Monitoring'], requiredInformation: ['Baselines', 'Targets'], expectedTimeline: 'Ongoing', dependencies: ['monitoring-setup'], outputs: ['Optimization Reports', 'Improvement Evidence'] },

  // ─── Governance ─────────────────────────────────────────────────────────────
  { id: 'compliance-audit', name: 'Compliance & Governance', category: 'governance', description: 'Regulatory compliance assessment (ISO 27001, SOC 2, NIST CSF)', businessValue: 'Regulatory compliance, audit readiness', deliverables: ['Compliance Report', 'Gap Analysis', 'Remediation Plan'], prerequisites: ['Policy documentation'], requiredInformation: ['Regulatory requirements', 'Current controls'], expectedTimeline: '3-6 weeks', dependencies: [], outputs: ['Compliance Assessment', 'Control Matrix'] },
  { id: 'vendor-management', name: 'Vendor Management', category: 'governance', description: 'Vendor relationship tracking, contract management, and performance monitoring', businessValue: 'Optimized vendor spend, reduced vendor risk', deliverables: ['Vendor Assessment', 'Contract Review'], prerequisites: ['Vendor contracts'], requiredInformation: ['Vendor list', 'Contracts', 'SLAs'], expectedTimeline: '2-4 weeks', dependencies: [], outputs: ['Vendor Register', 'Risk Assessment'] },
  { id: 'audit-trail', name: 'Audit Trail & Evidence', category: 'governance', description: 'Complete audit trail for all platform operations and decisions', businessValue: 'Traceability, accountability, compliance evidence', deliverables: ['Audit Reports', 'Evidence Trail'], prerequisites: [], requiredInformation: [], expectedTimeline: 'Ongoing', dependencies: [], outputs: ['Audit Logs', 'Evidence Reports'] },

  // ─── Financial / Commercial ─────────────────────────────────────────────────
  { id: 'financial-impact', name: 'Financial Impact Analysis', category: 'financial', description: 'Cost/benefit analysis, ROI projection, and investment prioritization', businessValue: 'Evidence-based investment decisions', deliverables: ['Financial Model', 'ROI Analysis'], prerequisites: ['Assessment data'], requiredInformation: ['Cost data', 'Business metrics'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Financial Report', 'Investment Recommendations'] },
  { id: 'commercial-engagement', name: 'Commercial Engagement', category: 'financial', description: 'Structured engagement, proposal, pricing, and approval workflow', businessValue: 'Controlled commercial lifecycle', deliverables: ['Engagement', 'Pricing', 'Proposal'], prerequisites: ['Service selection'], requiredInformation: ['Scope', 'Budget'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Engagement Record', 'Proposal', 'Approval'] },
  { id: 'payment-reconciliation', name: 'Payment & Reconciliation', category: 'financial', description: 'Payment method management, transaction tracking, and financial reconciliation', businessValue: 'Financial visibility, variance detection', deliverables: ['Payment Methods', 'Transactions', 'Reconciliation'], prerequisites: ['Engagement'], requiredInformation: ['Payment details'], expectedTimeline: 'Ongoing', dependencies: ['commercial-engagement'], outputs: ['Transaction Ledger', 'Reconciliation Reports'] },

  // ─── Intelligence ───────────────────────────────────────────────────────────
  { id: 'discovery-service', name: 'Infrastructure Discovery', category: 'intelligence', description: 'Automated discovery of applications, databases, servers, and dependencies', businessValue: 'Complete technology visibility', deliverables: ['Resource Inventory', 'Dependency Map'], prerequisites: ['Connector access'], requiredInformation: ['Environment credentials'], expectedTimeline: '1-2 days', dependencies: [], outputs: ['Discovery Results', 'Resource Count'] },
  { id: 'problem-identification', name: 'Problem Identification', category: 'intelligence', description: 'Automated problem detection from assessment and discovery evidence', businessValue: 'Proactive problem visibility', deliverables: ['Problem Catalogue', 'Priority Matrix'], prerequisites: ['Assessment'], requiredInformation: ['Discovery data'], expectedTimeline: 'Automatic', dependencies: ['discovery-service'], outputs: ['Problem Records', 'Risk Classification'] },
  { id: 'gap-analysis', name: 'Gap Analysis', category: 'intelligence', description: 'Current vs target state gap identification with maturity scoring', businessValue: 'Clear improvement roadmap', deliverables: ['Gap Register', 'Maturity Assessment'], prerequisites: ['Assessment'], requiredInformation: ['Target state'], expectedTimeline: 'Automatic', dependencies: ['discovery-service'], outputs: ['Gap Records', 'Maturity Scores'] },
  { id: 'recommendation-engine', name: 'Recommendation Engine', category: 'intelligence', description: 'Evidence-based recommendations from problems, gaps, and compliance data', businessValue: 'Actionable improvement suggestions', deliverables: ['Recommendations', 'Priority List'], prerequisites: ['Assessment data'], requiredInformation: [], expectedTimeline: 'Automatic', dependencies: [], outputs: ['Recommendations', 'Action Plan'] },
  { id: 'portfolio-intelligence', name: 'Portfolio Intelligence', category: 'intelligence', description: 'Cross-client analytics, patterns, and strategic insights', businessValue: 'Strategic decision support', deliverables: ['Portfolio Dashboard', 'Trend Analysis'], prerequisites: ['Multiple clients'], requiredInformation: [], expectedTimeline: 'Ongoing', dependencies: [], outputs: ['Portfolio Reports', 'Pattern Detection'] },
  { id: 'engineering-intelligence', name: 'Engineering Intelligence', category: 'intelligence', description: 'Advanced operational insights, defect patterns, and engineering recommendations', businessValue: 'Continuous engineering improvement', deliverables: ['Engineering Reports', 'Defect Analysis'], prerequisites: ['Operational data'], requiredInformation: [], expectedTimeline: 'Ongoing', dependencies: ['monitoring-setup'], outputs: ['Intelligence Reports', 'Improvement Actions'] },

  // ─── Platform / Support ─────────────────────────────────────────────────────
  { id: 'knowledge-management', name: 'Knowledge Management', category: 'support', description: 'Organizational knowledge capture, documentation, and sharing', businessValue: 'Reduced key-person risk, faster onboarding', deliverables: ['Knowledge Base', 'Runbooks'], prerequisites: ['Subject matter experts'], requiredInformation: ['Existing documentation'], expectedTimeline: 'Ongoing', dependencies: [], outputs: ['Knowledge Base', 'Training Materials'] },
  { id: 'notification-service', name: 'Notifications & Alerts', category: 'platform', description: 'Multi-channel notification delivery for workflow events and alerts', businessValue: 'Timely awareness, automated communication', deliverables: ['Notification Rules', 'Alert Configuration'], prerequisites: [], requiredInformation: ['Contact preferences'], expectedTimeline: '1 week', dependencies: [], outputs: ['Notifications', 'Delivery Reports'] },
  { id: 'workflow-automation', name: 'Workflow Automation', category: 'platform', description: 'Event-driven workflow rules, automated actions, and lifecycle management', businessValue: 'Reduced manual effort, consistent execution', deliverables: ['Workflow Rules', 'Automation Configuration'], prerequisites: [], requiredInformation: ['Business rules'], expectedTimeline: '1-2 weeks', dependencies: [], outputs: ['Automated Workflows', 'Event History'] },
  { id: 'client-portal', name: 'Client Portal', category: 'platform', description: 'Self-service client portal with journey visibility and executive dashboard', businessValue: 'Client transparency, reduced communication overhead', deliverables: ['Portal Access', 'Journey View', 'Executive Summary'], prerequisites: ['Client onboarding'], requiredInformation: [], expectedTimeline: 'Immediate', dependencies: [], outputs: ['Portal Dashboard', 'Journey Progress'] },
  { id: 'service-registry', name: 'Service Registry & Enablement', category: 'platform', description: 'Platform service catalog with per-client enablement, dependencies, and coverage', businessValue: 'Service governance, clear offering', deliverables: ['Service Catalog', 'Enablement Config'], prerequisites: [], requiredInformation: [], expectedTimeline: 'Immediate', dependencies: [], outputs: ['Service Registry', 'Coverage Reports'] },
];
