-- AskABD Platform Capability Registry Seed Data
-- Seeds the oc_capabilities table with all platform capabilities.
-- Status: operational | available | beta | planned | foundation
-- Maturity: 0 (planned) → 1 (foundation) → 2 (basic) → 3 (functional) → 4 (mature) → 5 (optimized)

INSERT INTO oc_capabilities (id, name, description, category, domain, business_problem, business_value, maturity, status, dependencies, related_services, related_apis, known_gaps, evidence, limitations, roadmap_phase, priority, owner, external_dependencies)
VALUES
-- ─── CORE PLATFORM (Operational) ───────────────────────────────────────────
('cap-client-onboarding', 'Client Onboarding', 'Automated enterprise client registration, OTP verification, and lifecycle initialization', 'core', 'platform', 'Manual client registration is slow, error-prone, and lacks audit trail', 'Reduce onboarding time from days to minutes with full audit and evidence', 4, 'operational', '[]', '["operations-center-service"]', '["/oc/clients", "/oc/otp/send", "/oc/otp/verify"]', '[]', '["OTP email delivery verified","Lifecycle auto-initialization tested","Multi-client isolation confirmed"]', '[]', 'current', 'critical', 'platform-team', '["SMTP (Mailpit in DEV)"]'),

('cap-lifecycle-management', 'Lifecycle Management', 'Server-authoritative client lifecycle with phase transitions, readiness gates, and audit', 'core', 'platform', 'No visibility into client journey progress or blockers', 'Full lifecycle visibility with automated gates preventing premature phase transitions', 4, 'operational', '["cap-client-onboarding"]', '["lifecycle-service"]', '["/oc/lifecycle/:clientId", "/oc/lifecycle/transition"]', '[]', '["Phase transitions validated","Readiness gates enforced","History tracked"]', '[]', 'current', 'critical', 'platform-team', '[]'),

('cap-requirements-management', 'Requirements Management', 'Service-specific requirement definitions, collection, validation, and readiness assessment', 'core', 'platform', 'Requirements are scattered, inconsistent, and hard to track across services', 'Centralized, versioned requirements with automated readiness scoring', 4, 'operational', '["cap-client-onboarding"]', '["requirements-service"]', '["/oc/client-services/:clientId/:serviceId/requirements"]', '[]', '["Requirement versioning active","Readiness scoring automated","Document attachment supported"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-document-management', 'Document Management', 'Enterprise document upload, versioning, validation, and secure storage', 'core', 'platform', 'Document collection is manual, versions are lost, validation is inconsistent', 'Automated document lifecycle with version history and structural validation', 3, 'operational', '["cap-requirements-management"]', '["document-storage-service"]', '["/oc/client-services/:clientId/:serviceId/requirements/:key/documents"]', '["No OCR/content extraction yet","No expiry auto-notification"]', '["Binary upload tested","Version superseding verified","MIME validation active"]', '["OCR integration planned","Auto-expiry alerts planned"]', 'current', 'medium', 'platform-team', '[]'),

('cap-audit-trail', 'Audit Trail', 'Comprehensive audit logging of all platform operations with evidence capture', 'core', 'governance', 'No audit trail for compliance, forensics, or operational review', 'Complete operational history for compliance, debugging, and evidence', 4, 'operational', '[]', '["operations-center-service"]', '["/oc/audit"]', '[]', '["All write operations audited","Evidence array captured","Entity-level filtering available"]', '[]', 'current', 'critical', 'platform-team', '[]'),

('cap-notification-engine', 'Notification Engine', 'Multi-channel notification delivery (email, in-app) with templates', 'core', 'platform', 'No automated stakeholder communication during client operations', 'Automated, audited notifications reduce manual communication overhead', 3, 'operational', '[]', '["notification-service"]', '["/oc/notifications"]', '["SMS channel not implemented","Push notifications planned"]', '["Email delivery via SMTP tested","Notification history queryable"]', '["SMS integration","Push notification","Template engine"]', 'current', 'medium', 'platform-team', '["SMTP provider"]'),

-- ─── DISCOVERY & ASSESSMENT ────────────────────────────────────────────────
('cap-connector-framework', 'Connector Framework', 'Universal database and service connector with validation and security levels', 'discovery', 'integration', 'Manual connection setup is error-prone and lacks security controls', 'Validated, secure connections with step-by-step diagnostic output', 4, 'operational', '["cap-client-onboarding"]', '["connector-service"]', '["/oc/connectors/test", "/oc/connectors/save"]', '["Limited to PostgreSQL connectors currently"]', '["Connection validation with step diagnostics","Security level enforcement","Auto-validate on save"]', '["Cloud provider connectors (AWS RDS, Azure SQL)","NoSQL connectors"]', 'current', 'high', 'platform-team', '["Target database access"]'),

('cap-discovery-engine', 'Discovery Engine', 'Automated infrastructure and schema discovery with resource cataloging', 'discovery', 'assessment', 'Manual infrastructure inventory is incomplete, outdated, and labor-intensive', 'Automated resource discovery with dependency mapping and evidence capture', 4, 'operational', '["cap-connector-framework"]', '["discovery-service"]', '["/oc/discovery/start", "/oc/discovery/:clientId"]', '[]', '["Schema discovery automated","Resource cataloging complete","Auto-problem detection integrated"]', '["Cloud resource discovery (AWS/Azure/GCP)"]', 'current', 'high', 'platform-team', '["Database connectivity"]'),

('cap-assessment-engine', 'Assessment Engine', 'Multi-dimensional risk and health assessment with scoring and findings', 'discovery', 'assessment', 'No standardized way to assess client environment health and risk', 'Objective, evidence-based risk scoring with actionable findings', 4, 'operational', '["cap-discovery-engine"]', '["assessment-service"]', '["/oc/assessment/start", "/oc/assessment/:clientId"]', '[]', '["Risk scoring operational","Finding categorization active","Auto-import to Problem Universe"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-recommendation-engine', 'Recommendation Engine', 'AI-assisted recommendation generation from assessment findings', 'discovery', 'advisory', 'Recommendations require expensive consultant time and are inconsistent', 'Consistent, evidence-based recommendations generated in seconds', 3, 'operational', '["cap-assessment-engine"]', '["recommendation-service"]', '["/oc/recommendations/generate", "/oc/recommendations/:id/approve"]', '["No ML model yet - rule-based","Limited to database domain recommendations"]', '["Recommendation generation tested","Approve/reject workflow active"]', '["ML-powered recommendations","Cross-domain recommendation engine"]', 'current', 'medium', 'platform-team', '[]'),

-- ─── PROBLEM & DECISION ────────────────────────────────────────────────────
('cap-problem-universe', 'Problem Universe', 'Enterprise problem discovery, classification, evidence, and impact tracking', 'analysis', 'problem-management', 'Problems are discovered ad-hoc, lack evidence, and have no financial quantification', 'Systematic problem identification with financial impact and effort estimation', 4, 'operational', '["cap-assessment-engine","cap-discovery-engine"]', '["problem-universe-service"]', '["/oc/clients/:clientId/problems", "/oc/problems/:id"]', '[]', '["Auto-detection from discovery","Auto-import from assessment","Financial/effort estimation","Idempotent operations"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-gap-analysis', 'Gap Analysis', 'Current vs target state gap identification with maturity scoring and prioritization', 'analysis', 'strategic-planning', 'No structured approach to identify and prioritize capability gaps', 'Prioritized gap portfolio with maturity scoring and remediation planning', 4, 'operational', '["cap-problem-universe"]', '["gap-analysis-service"]', '["/oc/clients/:clientId/gaps", "/oc/gaps/:id"]', '[]', '["Auto-generation from problems","Target state workflow","Priority scoring","Aging/overdue detection"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-decision-framework', 'Decision Framework', 'Structured option comparison, weighted scoring, and audited decision records', 'analysis', 'decision-support', 'Decisions are made without structured comparison or audit trail', 'Evidence-based decisions with weighted comparison and full audit', 4, 'operational', '["cap-gap-analysis"]', '["decision-transformation-service"]', '["/oc/gaps/:id/options", "/oc/gaps/:id/compare", "/oc/gaps/:id/decide"]', '[]', '["Weighted scoring engine","Multi-factor comparison","Decision audit trail"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-transformation-planning', 'Transformation Planning', 'Transformation plan creation with phases, milestones, and rollback strategies', 'execution', 'transformation', 'Transformation plans are ad-hoc, lack rollback strategies, and have no tracking', 'Structured transformation plans with phases, success criteria, and rollback', 3, 'operational', '["cap-decision-framework"]', '["decision-transformation-service"]', '["/oc/clients/:clientId/transformations"]', '["No Gantt/timeline visualization yet","No resource allocation"]', '["Plan creation tested","Status lifecycle active","Rollback strategy captured"]', '["Timeline visualization","Resource allocation","Dependency tracking"]', 'current', 'medium', 'platform-team', '[]'),

-- ─── MIGRATION & VALIDATION ────────────────────────────────────────────────
('cap-migration-preflight', 'Migration Pre-Flight', 'Pre-migration readiness validation with blocker identification', 'execution', 'migration', 'Migrations fail due to undetected prerequisites and configuration issues', 'Prevent migration failures by validating all prerequisites upfront', 3, 'operational', '["cap-discovery-engine","cap-connector-framework"]', '["migration-validation-service"]', '["/oc/migration/preflight", "/oc/production/readiness"]', '[]', '["Preflight checks operational","Production readiness gate active"]', '[]', 'current', 'high', 'platform-team', '[]'),

('cap-migration-execution', 'Migration Execution', 'Controlled migration execution with dry-run, progress tracking, and rollback', 'execution', 'migration', 'Migrations are risky, manual, and lack rollback capability', 'Safe, controlled migration with dry-run validation and instant rollback', 3, 'operational', '["cap-migration-preflight"]', '["migration-execution-service"]', '["/oc/migration/plan", "/oc/migration/execute", "/oc/migration/:id/rollback"]', '["Limited to schema migration","No data migration yet"]', '["Dry-run tested","Rollback verified","Progress tracking active"]', '["Data migration engine","Zero-downtime migration","Multi-database orchestration"]', 'current', 'high', 'platform-team', '["Target database write access"]'),

('cap-migration-validation', 'Post-Migration Validation', 'Post-migration integrity validation with row counts, schema comparison, and drift detection', 'execution', 'migration', 'No way to verify migration correctness beyond manual spot-checks', 'Automated validation confirms data integrity and identifies drift', 3, 'operational', '["cap-migration-execution"]', '["migration-execution-service"]', '["/oc/migration/:id/validate"]', '[]', '["Row count validation","Schema comparison","Drift classification (expected vs unexpected)"]', '["Checksum validation","Referential integrity validation"]', 'current', 'high', 'platform-team', '[]'),

-- ─── PLATFORM SERVICES & HEALTH ────────────────────────────────────────────
('cap-platform-health', 'Platform Health Monitoring', 'Real-time platform service health with dependency graph and environment detection', 'infrastructure', 'observability', 'No visibility into platform service health or dependencies', 'Instant health visibility with auto-detection and recovery suggestions', 3, 'operational', '[]', '["platform-services-routes"]', '["/platform/services/health"]', '["No historical metrics storage","No alerting"]', '["Multi-service health checks","Environment detection","Dependency mapping"]', '["Metrics time-series","Alert rules","SLA tracking"]', 'current', 'medium', 'platform-team', '[]'),

('cap-service-recovery', 'One-Click Service Recovery', 'Allowlisted service recovery via Docker restart with health polling', 'infrastructure', 'resilience', 'Service recovery requires SSH access and manual container management', 'One-click recovery for approved services with health confirmation', 3, 'operational', '["cap-platform-health"]', '["platform-services-routes"]', '["/platform/services/recover"]', '["Limited to Docker restart","No auto-recovery"]', '["Allowlisted recovery tested","Health polling confirmation","Recovery audit"]', '["Auto-recovery rules","Kubernetes integration","Multi-node recovery"]', 'current', 'low', 'platform-team', '["Docker socket access"]'),

('cap-capability-registry', 'Platform Capability Registry', 'Self-documenting registry of all platform capabilities with maturity and roadmap tracking', 'infrastructure', 'governance', 'No inventory of platform capabilities, their status, or evolution roadmap', 'Complete capability visibility with maturity tracking and gap identification', 3, 'operational', '[]', '["capability-registry-service"]', '["/oc/capabilities", "/oc/capabilities/summary"]', '[]', '["Registry seeded with all capabilities","CRUD operations available","Summary/roadmap views"]', '[]', 'current', 'medium', 'platform-team', '[]'),

-- ─── SECURITY & GOVERNANCE ─────────────────────────────────────────────────
('cap-authentication', 'Authentication Framework', 'JWT-based authentication with dev bypass and public route configuration', 'security', 'identity', 'No standardized authentication across platform APIs', 'Consistent authentication with configurable bypass for development', 3, 'operational', '[]', '["auth-middleware"]', '[]', '["No refresh token rotation","No MFA beyond OTP"]', '["JWT validation active","Public route whitelist","Dev bypass for local development"]', '["Refresh token rotation","OAuth2/OIDC provider integration","Session management"]', 'current', 'critical', 'security-team', '[]'),

('cap-authorization', 'Authorization (RBAC)', 'Role-based access control with route-level rules and policy enforcement', 'security', 'identity', 'No fine-grained access control beyond authentication', 'Role-based access with configurable rules and audit', 3, 'operational', '["cap-authentication"]', '["rbac-middleware"]', '[]', '["No attribute-based policies (ABAC)","No dynamic role assignment"]', '["Route-level RBAC active","Default policy enforcement","Dev bypass configurable"]', '["ABAC policies","Dynamic role assignment","Tenant-level isolation"]', 'current', 'high', 'security-team', '[]'),

('cap-rate-limiting', 'Rate Limiting', 'Token-bucket rate limiting with per-route and per-user controls', 'security', 'resilience', 'No protection against API abuse or accidental DDoS', 'Protection against abuse with configurable per-route limits', 3, 'operational', '[]', '["rate-limit-middleware"]', '[]', '["No distributed rate limiting","No adaptive throttling"]', '["Token bucket algorithm active","Per-route configuration"]', '["Redis-backed distributed limiting","Adaptive throttling","Circuit breaker integration"]', 'current', 'medium', 'security-team', '[]'),

-- ─── PLANNED / FOUNDATION ──────────────────────────────────────────────────
('cap-optimization-engine', 'Continuous Optimization Engine', 'Post-transformation optimization with performance monitoring and cost tracking', 'optimization', 'continuous-improvement', 'No systematic approach to optimize after initial transformation', 'Ongoing optimization identifies savings opportunities and performance improvements', 0, 'planned', '["cap-transformation-planning","cap-platform-health"]', '[]', '[]', '["Requires transformation execution data","Requires metrics collection"]', '[]', '["Performance baseline collection","Cost anomaly detection","Optimization recommendations"]', 'next', 'high', 'platform-team', '["Metrics provider (CloudWatch/Datadog)"]'),

('cap-portfolio-management', 'Transformation Portfolio', 'Cross-client transformation portfolio with resource allocation and progress tracking', 'execution', 'portfolio', 'No visibility across multiple client transformations for resource planning', 'Portfolio-level visibility enables resource optimization and risk management', 0, 'planned', '["cap-transformation-planning"]', '[]', '[]', '["Requires multiple active transformations","Requires resource tracking"]', '[]', '["Portfolio dashboard","Resource allocation","Cross-client risk analysis"]', 'next', 'medium', 'platform-team', '[]'),

('cap-knowledge-base', 'Enterprise Knowledge Base', 'Organizational knowledge capture, pattern library, and best practices repository', 'advisory', 'knowledge-management', 'Lessons learned are lost, patterns are not reused, expertise leaves with people', 'Captured organizational knowledge accelerates future engagements', 0, 'planned', '["cap-problem-universe","cap-gap-analysis"]', '[]', '[]', '["Requires pattern detection from historical data"]', '[]', '["Pattern library","Lesson capture","Best practice templates"]', 'future', 'medium', 'platform-team', '[]'),

('cap-client-portal', 'Client Self-Service Portal', 'Client-facing portal with progress visibility, document submission, and communication', 'core', 'client-experience', 'Clients have no self-service visibility into their engagement progress', 'Reduce communication overhead and improve client satisfaction with self-service', 0, 'planned', '["cap-lifecycle-management","cap-document-management"]', '[]', '[]', '["Requires client-specific authentication","Requires permission model"]', '[]', '["Progress dashboard","Document upload","Communication channel"]', 'future', 'medium', 'product-team', '[]'),

('cap-integration-marketplace', 'Integration Marketplace', 'Pre-built connectors and integration templates for common enterprise systems', 'discovery', 'integration', 'Each new integration requires custom development from scratch', 'Pre-built integrations reduce time-to-value for new client environments', 0, 'planned', '["cap-connector-framework"]', '[]', '[]', '["Requires connector standardization","Requires marketplace infrastructure"]', '[]', '["Connector templates","One-click activation","Community contributions"]', 'future', 'low', 'platform-team', '["Cloud provider SDKs"]'),

('cap-compliance-automation', 'Compliance Automation', 'Automated compliance checking against regulatory frameworks (SOC2, ISO27001, GDPR)', 'security', 'compliance', 'Compliance verification is manual, expensive, and point-in-time', 'Continuous compliance monitoring reduces audit cost and improves posture', 0, 'planned', '["cap-audit-trail","cap-authorization"]', '[]', '[]', '["Requires compliance rule definitions","Requires evidence collection framework"]', '[]', '["Compliance rule engine","Evidence auto-collection","Audit report generation"]', 'future', 'high', 'security-team', '["Compliance framework definitions"]'),

('cap-ai-advisory', 'AI-Powered Advisory', 'Machine learning recommendations, pattern detection, and predictive analytics', 'advisory', 'ai-ml', 'Recommendations are rule-based and cannot learn from historical outcomes', 'ML-powered insights improve recommendation quality and predict outcomes', 0, 'planned', '["cap-recommendation-engine","cap-knowledge-base"]', '[]', '[]', '["Requires training data from outcomes","Requires ML infrastructure"]', '[]', '["Outcome prediction","Pattern detection","Anomaly identification"]', 'future', 'medium', 'ai-team', '["ML infrastructure (SageMaker/Vertex AI)"]'),

('cap-multi-tenancy', 'Multi-Tenancy Platform', 'Full tenant isolation with per-tenant configuration, data partitioning, and billing', 'core', 'platform', 'Platform cannot safely serve multiple organizations with proper isolation', 'Enable platform-as-a-service model with proper tenant isolation', 1, 'foundation', '["cap-authentication","cap-authorization"]', '[]', '[]', '["Client isolation exists at data level","No billing integration","No per-tenant config"]', '["Client-level data isolation via client_id"]', '["Tenant configuration","Data partitioning","Usage metering","Billing integration"]', 'next', 'high', 'platform-team', '["Billing provider (Stripe)"]'),

('cap-event-driven', 'Event-Driven Architecture', 'Async event bus for cross-service communication and workflow orchestration', 'infrastructure', 'architecture', 'Services are tightly coupled via synchronous HTTP calls', 'Loose coupling enables independent scaling and resilient workflows', 1, 'foundation', '[]', '[]', '[]', '["Current system uses direct function calls","No message broker"]', '["Lifecycle transitions emit implicit events"]', '["Event bus (SNS/SQS or Kafka)","Event schema registry","Dead letter queue","Replay capability"]', 'next', 'high', 'platform-team', '["Message broker (SQS/Kafka)"]'),

('cap-observability', 'Full Observability Stack', 'Distributed tracing, metrics collection, log aggregation, and dashboards', 'infrastructure', 'observability', 'Limited visibility into system behavior beyond basic health checks', 'Full observability enables proactive issue detection and performance optimization', 1, 'foundation', '["cap-platform-health"]', '[]', '[]', '["Correlation IDs implemented","Structured logging active","No metrics storage"]', '["Request correlation via x-request-id","Structured JSON logging"]', '["OpenTelemetry tracing","Prometheus metrics","Grafana dashboards","Alert manager"]', 'next', 'high', 'platform-team', '["OpenTelemetry collector","Prometheus","Grafana"]'),

('cap-ci-cd', 'CI/CD Pipeline', 'Automated build, test, and deployment pipeline with environment promotion', 'infrastructure', 'devops', 'Deployments are manual and error-prone with no automated quality gates', 'Automated deployment with quality gates reduces risk and increases velocity', 1, 'foundation', '[]', '[]', '[]', '["No automated deployment pipeline","Manual testing required"]', '["Build scripts available (npm run build)","Test suite available (vitest)"]', '["GitHub Actions pipeline","Automated testing","Environment promotion","Rollback automation"]', 'next', 'high', 'devops-team', '["GitHub Actions","Container registry"]'),

('cap-disaster-recovery', 'Disaster Recovery', 'Automated backup, cross-region replication, and recovery procedures', 'infrastructure', 'resilience', 'No documented or tested disaster recovery procedure', 'Proven recovery capability with defined RTO/RPO and regular testing', 0, 'planned', '["cap-platform-health","cap-observability"]', '[]', '[]', '["Database is Docker volume (single node)","No cross-region replication"]', '["Docker volume persistence"]', '["Automated backups","Cross-region replication","Recovery testing","RTO/RPO documentation"]', 'future', 'high', 'infrastructure-team', '["Cloud storage (S3)","Cross-region infrastructure"]')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  domain = EXCLUDED.domain,
  business_problem = EXCLUDED.business_problem,
  business_value = EXCLUDED.business_value,
  maturity = EXCLUDED.maturity,
  status = EXCLUDED.status,
  dependencies = EXCLUDED.dependencies,
  related_services = EXCLUDED.related_services,
  related_apis = EXCLUDED.related_apis,
  known_gaps = EXCLUDED.known_gaps,
  evidence = EXCLUDED.evidence,
  limitations = EXCLUDED.limitations,
  roadmap_phase = EXCLUDED.roadmap_phase,
  priority = EXCLUDED.priority,
  owner = EXCLUDED.owner,
  external_dependencies = EXCLUDED.external_dependencies,
  updated_at = NOW();
