-- AskABD Future Capability Placeholders
-- Status: planned/concept. DO NOT mark operational without implementation evidence.

INSERT INTO oc_capabilities (id, name, description, category, domain, business_problem, business_value, maturity, status, dependencies, roadmap_phase, priority, owner)
VALUES
-- CLOUD
('cap-aws-discovery', 'AWS Resource Discovery', 'Automated discovery of AWS infrastructure, databases, and services', 'discovery', 'cloud', 'Manual AWS inventory is incomplete and outdated', 'Automated cloud asset visibility', 0, 'planned', '["cap-connector-framework"]', 'next', 'high', 'platform-team'),
('cap-azure-discovery', 'Azure Resource Discovery', 'Automated discovery of Azure resources and services', 'discovery', 'cloud', 'No visibility into Azure environment', 'Automated Azure asset inventory', 0, 'planned', '["cap-connector-framework"]', 'next', 'high', 'platform-team'),
('cap-gcp-discovery', 'GCP Resource Discovery', 'Automated discovery of Google Cloud resources', 'discovery', 'cloud', 'No visibility into GCP environment', 'Automated GCP asset inventory', 0, 'planned', '["cap-connector-framework"]', 'future', 'medium', 'platform-team'),
('cap-cloud-cost', 'Cloud Cost Optimization', 'Identify cloud cost savings through rightsizing, reservations, and waste elimination', 'optimization', 'cloud', 'Cloud spend growing without visibility into waste', 'Reduce cloud costs 20-40%', 0, 'planned', '["cap-aws-discovery"]', 'next', 'high', 'platform-team'),
('cap-cloud-security', 'Cloud Security Assessment', 'Assess cloud security posture against best practices', 'security', 'cloud', 'Unknown cloud security gaps', 'Proactive cloud security posture', 0, 'planned', '["cap-aws-discovery"]', 'next', 'high', 'security-team'),
('cap-k8s-assessment', 'Kubernetes Assessment', 'Assess Kubernetes clusters for security, performance, and best practices', 'discovery', 'cloud', 'K8s complexity without standardized assessment', 'Optimized container infrastructure', 0, 'concept', '["cap-aws-discovery"]', 'future', 'medium', 'platform-team'),
-- TECHNOLOGY
('cap-app-portfolio', 'Application Portfolio Management', 'Rationalize and manage the enterprise application landscape', 'analysis', 'application', 'No visibility into full application portfolio', 'Application rationalization and cost reduction', 0, 'planned', '["cap-discovery-engine"]', 'next', 'high', 'platform-team'),
('cap-tech-debt', 'Technical Debt Assessment', 'Identify and quantify technical debt across the technology portfolio', 'analysis', 'application', 'Hidden technical debt increasing risk', 'Quantified debt with remediation roadmap', 0, 'planned', '["cap-discovery-engine","cap-assessment-engine"]', 'next', 'medium', 'platform-team'),
('cap-eol-intelligence', 'EOL/EOS Intelligence', 'Track technology end-of-life and end-of-support dates', 'analysis', 'application', 'Unexpected EOL creates security and support risks', 'Proactive lifecycle planning', 0, 'planned', '["cap-discovery-engine"]', 'next', 'high', 'platform-team'),
('cap-legacy-modernization', 'Legacy Modernization', 'Structured modernization of legacy applications and infrastructure', 'execution', 'application', 'Legacy systems increasing cost and risk', 'Modernized technology with reduced TCO', 0, 'planned', '["cap-app-portfolio","cap-tech-debt"]', 'next', 'high', 'platform-team'),
-- DATA
('cap-data-quality', 'Data Quality Engine', 'Automated data quality assessment and monitoring', 'analysis', 'data', 'Unknown data quality issues affecting decisions', 'Trusted data for business decisions', 0, 'concept', '["cap-discovery-engine"]', 'future', 'medium', 'platform-team'),
('cap-data-governance', 'Data Governance', 'Enterprise data governance policies and enforcement', 'security', 'data', 'No standardized data governance', 'Controlled data access and quality', 0, 'concept', '["cap-data-quality"]', 'future', 'medium', 'platform-team'),
('cap-data-catalog', 'Data Catalog', 'Searchable catalog of enterprise data assets', 'discovery', 'data', 'Data assets are undocumented and hard to find', 'Self-service data discovery', 0, 'concept', '["cap-discovery-engine"]', 'future', 'low', 'platform-team'),
-- SECURITY
('cap-vuln-management', 'Vulnerability Management', 'Continuous vulnerability detection and remediation tracking', 'security', 'security', 'Vulnerabilities remain undetected or unresolved', 'Proactive vulnerability posture', 0, 'planned', '["cap-discovery-engine","cap-assessment-engine"]', 'next', 'high', 'security-team'),
('cap-security-posture', 'Security Posture Management', 'Unified security posture scoring and improvement tracking', 'security', 'security', 'No unified view of security health', 'Measurable security improvement', 0, 'planned', '["cap-vuln-management","cap-compliance-automation"]', 'next', 'high', 'security-team'),
-- TRANSFORMATION
('cap-tfm-templates', 'Transformation Templates', 'Reusable transformation playbooks for common scenarios', 'execution', 'transformation', 'Every transformation starts from scratch', 'Accelerated transformation with proven patterns', 0, 'planned', '["cap-transformation-planning"]', 'next', 'medium', 'platform-team'),
('cap-tfm-readiness', 'Transformation Readiness', 'Structured readiness assessment before transformation execution', 'execution', 'transformation', 'Transformations start without verifying prerequisites', 'Reduced transformation failure rate', 0, 'planned', '["cap-migration-preflight"]', 'next', 'medium', 'platform-team'),
('cap-change-management', 'Change Management', 'Enterprise change management for transformation programs', 'execution', 'transformation', 'Change resistance causes transformation failure', 'Structured change adoption', 0, 'concept', '["cap-transformation-planning"]', 'future', 'medium', 'platform-team'),
-- COMPLIANCE
('cap-pci-dss', 'PCI DSS Compliance', 'Payment Card Industry Data Security Standard compliance', 'security', 'compliance', 'PCI DSS audit preparation is manual and incomplete', 'Automated PCI compliance tracking', 0, 'planned', '["cap-compliance-automation"]', 'next', 'medium', 'security-team'),
('cap-gdpr', 'GDPR Compliance', 'General Data Protection Regulation compliance management', 'security', 'compliance', 'GDPR compliance requires ongoing evidence', 'Continuous GDPR compliance posture', 0, 'planned', '["cap-compliance-automation"]', 'next', 'medium', 'security-team'),
('cap-hipaa', 'HIPAA Compliance', 'Health Insurance Portability and Accountability Act compliance', 'security', 'compliance', 'Healthcare data protection requirements', 'HIPAA compliance for health organizations', 0, 'planned', '["cap-compliance-automation"]', 'future', 'medium', 'security-team'),
-- BUSINESS
('cap-business-case', 'Business Case Generation', 'Automated business case creation from assessment and financial data', 'advisory', 'business', 'Business cases are manually created and inconsistent', 'Evidence-based business cases in minutes', 0, 'planned', '["cap-problem-universe","cap-gap-analysis","cap-decision-framework"]', 'next', 'high', 'platform-team'),
('cap-vendor-eval', 'Vendor Evaluation', 'Structured vendor assessment and comparison', 'analysis', 'business', 'Vendor selection is subjective', 'Objective vendor comparison with scoring', 0, 'concept', '["cap-decision-framework"]', 'future', 'low', 'platform-team'),
('cap-exec-reporting', 'Executive Reporting', 'Automated executive transformation reports and dashboards', 'advisory', 'business', 'Executive reporting is manual and delayed', 'Real-time executive visibility', 0, 'planned', '["cap-portfolio-management","cap-engineering-intelligence"]', 'next', 'medium', 'platform-team'),
-- INTELLIGENCE
('cap-predictive', 'Predictive Intelligence', 'ML-powered prediction of transformation risks and outcomes', 'advisory', 'intelligence', 'Cannot predict transformation success probability', 'Evidence-based outcome prediction', 0, 'concept', '["cap-optimization-engine","cap-engineering-intelligence"]', 'future', 'medium', 'ai-team'),
('cap-benchmarking', 'Industry Benchmarking', 'Compare client metrics against industry benchmarks', 'advisory', 'intelligence', 'No context for whether metrics are good or bad', 'Industry-contextualized performance', 0, 'concept', '["cap-portfolio-management"]', 'future', 'low', 'platform-team'),
-- INDUSTRY
('cap-ind-banking', 'Banking Industry Module', 'Banking-specific transformation patterns and compliance', 'core', 'industry', 'Generic transformation missing banking context', 'Banking-aware transformation', 0, 'concept', '[]', 'future', 'low', 'industry-team'),
('cap-ind-healthcare', 'Healthcare Industry Module', 'Healthcare-specific compliance and transformation', 'core', 'industry', 'Healthcare has unique regulatory requirements', 'HIPAA-aware healthcare transformation', 0, 'concept', '["cap-hipaa"]', 'future', 'low', 'industry-team'),
('cap-ind-manufacturing', 'Manufacturing Industry Module', 'Manufacturing OT/IT convergence and modernization', 'core', 'industry', 'Manufacturing legacy systems are high-risk', 'Safe manufacturing technology modernization', 0, 'concept', '[]', 'future', 'low', 'industry-team')
ON CONFLICT (id) DO NOTHING;
